title: Networks in Science of Science
description: "A NetSci 2025 Satellite Workshop"

timezone: Europe/Vienna

navigation:
  Home: "/2025/"
  Call for Papers: "/2025/cfp"
  Accepted Papers: "/2025/papers"
  Speakers: "/2025/speakers"
  Schedule: "/2025/schedule"
  Organizers: "/2025/organizers"
  Back: "https://netscisci.github.io/"

markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
